### PR TITLE
Merging Document MQM support

### PR DESCRIPTION
**Pull request by snukky**
@zouharvi, this is a branch mentioned in #122.

### CODE REVIEW

**Comment by zouharvi** [comment]
Hi, thanks for the extra commits and the reviewing!

I'm getting an error for the MQM task from this PR. Investigating now.

**Comment by zouharvi** [comment]
Hi, thanks for the extra commits and reviewing!
- The MQM/LQM tasks seem to work well.
- I noticed that the default `batches.json` in `Examples/DirectMQM` is not good because it's not document-level. I'll upload a different example but not sure where, given that there are two PRs/branches now.

**Comment by snukky** [comment]
I will try to add you as a collaborator (asked Christian) so that you can push to this branch directly. Until then, let's open a PR against this branch, and I will be pulling them.

Once you have the updated batches.json for Examples, can you also add a regression test for both tasks? I would suggest starting with the pairwise first.

**Comment by snukky** [comment]
A note to myself: the pipeline `testing` is green, but 2 regression tests are failing. Can be seen if you click on job.

**Comment by zouharvi** [comment]
> I will try to add you as a collaborator (asked Christian) so that you can push to this branch directly. Until then, let's open a PR against this branch, and I will be pulling them.
> 
> Once you have the updated batches.json for Examples, can you also add a regression test for both tasks? I would suggest starting with the pairwise first.

Not sure what you mean by "both tasks". There's only one new one, direct document MQM. The PR is here: #129.

**Pull request merged**
