### PR TITLE
Capitalize 'deutsch'

### PR DESCRIPTION
**Pull request by snukky**
Changes proposed in the pull request:
- `German (deutsch)` => `German (Deutsch)`

@AppraiseDev/core-team

### CODE REVIEW

**Comment by kocmitom** [comment]
What about the other languages? Shouldn't they be capitalized as well?

**Comment by snukky** [comment]
I think we want to show the language name as it should be shown in that language. For German it should be capitalized. Maybe there are errors for other languages, but that's beyond my expertise.

**Comment by kocmitom** [comment]
Good point, I haven't thought about it that way.

**Comment by snukky** [comment]
Closing. Superseded by/included in #73

**Pull request closed without merging**
