### PR TITLE
Compute document-level annotation times.

### PR DESCRIPTION
**Pull request by zouharvi**
For MQM/ESA we are collecting `(first_segment_edit, last_segment_edit)`. We decided to keep this, but for the admin status and dashboard, we want a more accurate times. For this, we use the first edit overall _for a document_ and last edit overall _for a document_.

The changes are done in:
- DirectAssesementDocumentResult (for dashboard)
- Campaign status page

They will only apply if `ESA` or `MQM` is in the campaign options. The times still go through the filtering.

### CODE REVIEW

**Comment by zouharvi** [comment]
I don't know why the other commits are listed, since I pulled from `origin/develop` before. However, there are only two files edited in this PR so should be safe.

**Comment by zouharvi** [comment]
Added one smaller commit that clears up something that's been bothering me for a while.

**Review by snukky — APPROVED** [review]
I think I have missed this PR before, but it looks good. Feel free to merge at your convenience. Thanks.

**Comment by zouharvi** [comment]
Oh, so the last campaigns weren't run with this? That means that the vendor/users were seeing the old times. Hopefully that's not too off.

**Pull request merged**
