### PR TITLE
add Maithili and Sanskrit

### PR DESCRIPTION
**Pull request by hitokazm**
Add Maithili and Sanskrit language codes

### CODE REVIEW

**Review by cfedermann — APPROVED** [review]
Thanks, @hitokazm

**Comment by cfedermann** [comment]
Please fix the failing checks

**Comment by hitokazm** [comment]
@cfedermann, @snukky, the validation failed at line https://github.com/AppraiseDev/Appraise/actions/runs/3252917786/jobs/5339661096#step:4:112, and it is a known mypy bug for Python 3.10.7 as discussed in https://github.com/python/mypy/issues/13627 (guessing the validation uses the python version).

Do you see any issues using mypy>=0.981 for this code validation?

**Review by snukky — APPROVED** [review]

**Comment by snukky** [comment]
The issue that causes the formatting checks to fail is unrelated to the PR, so I believe that the correct approach in such situations is to open a bug report (#98) and merge the PR to not block any work.

**Pull request merged**
